# Generated by Django 5.0.4 on 2024-04-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=30)),
                ('quadra', models.IntegerField()),
                ('lado', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('focos_encontrados', models.CharField(max_length=150)),
                ('acoes_realizadas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadra', models.CharField(max_length=100)),
                ('lado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
